/**
 * 这里主要定义数据库常见的错误类型
 */
export default{
    ER_PASSWORD_ANONYMOUS_USER:1131,//匿名密码错误
    ER_PASSWORD_NOT_ALLOWED:1132,//
    ER_PASSWORD_NO_MATCH:1133,//密码不匹配
    ER_ACCESS_DENIED_NO_PASSWORD_ERROR:1698,//密码错误拒绝访问
    ER_SET_PASSWORD_AUTH_PLUGIN:1699,//
}